spring:
  application:
    name: merchant
  data:
    mongodb:
      #uri: ${MONGOURI}
#      uri: mongodb://root:mongolocalprotavao@localhost:27017/DeliveryApp?authSource=admin
        uri: mongodb://admin:password@database:27017/DeliveryApp?authSource=admin
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8084

#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}-${random.int}
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#    register-with-eureka: true

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: actuator,logfile,metrics,health,info
      base-path: /v1/actuator

jwt:
  config:
    type: signed

security:
  ignored: /swagger-resources/**

google-maps:
  access-key: ${REACT_APP_GOOGLE_MAPS_KEY}
  distance-calculator: https://maps.googleapis.com/maps/api/distancematrix/json?
  geocode: https://maps.googleapis.com/maps/api/geocode/json?