spring:
  application:
    name: order
  data:
    mongodb:
      #uri: ${MONGOURI}
      uri: mongodb://root:mongolocalprotavao@localhost:27017/DeliveryApp?authSource=admin
#          uri: mongodb://admin:password@database:27017/DeliveryApp?authSource=admin
  main:
    allow-bean-definition-overriding: true
#  rabbitmq:
#    host: rabbitmq
#    port: 5672

server:
  port: 8085
#
#eureka:
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.application.name}-${random.int}
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#    register-with-eureka: true

jwt:
  config:
    type: signed

security:
  ignored: /swagger-resources/**
  access-token: Bearer eyJjdHkiOiJKV1QiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2IiwiYWxnIjoiZGlyIn0..ZjSwixPU2qGoMP8BRQzywQ.wZ1tbCFXauTK6CMon8LmCQDIpXkyChUxhUDC0iuueHUTujVy3vb9Gmh_WEz3tyRILMWWQ56x8QHrsqGuCIU5E0ulqIHFbfahu71h0F-gc_Hw4JW70hSCQ5FVakVSJf3Bl0h2LHWZJ3wnvfNGxZgKacTH_Oh9mi1rXNfNmbsaA4XCUvz0pxXPAn1IjeYzb1t2LHDl6uVC6F42Mpj_Lt2plTo6zvp3rkOUFMYMhTgs9w-SxSlhD_Qz7fWBnF1vg0BPHAGc5SPHG8-ekuvntMwi1gnj3yb7X2Kr5ssjiyCVqLPJs2fCIOhlSYK4Amn9Wldef7uG5eps3kgvaukEGaGwOQecss4Si2rKr8c-w8d2cdGmpnWaaEsBfNZKzYlTJNVgir77Z8PBWqyC8kP0YqHPE3OKJz-zc0PEJltpwWZPMEzyYFWdCTWA7RxaS2vQkcS8r3hpfK8HYT3dlyadQRCIVENJjR8b1qw9_H6B5cZ3l1u17qhv2nZMX0j8sNuO6mN-Aj7vHLs32-zzc1xcBwQhguxdpQQLeBZxqj8LMOru07PCnDP7Mli1Nreumv8JeEsP0XhFVUNq63mXAlJjyZ04UhbXgQ-AAOUt4FXfWZ3f0hOVY5_zXSYdSMweQ3y7ld8bhKQPPHNz6AqZHqrBmpSrZE_be7DopsADl8w22-fnIVjYFk-x2FXGXH2yv9M6CzXBrYY2VImRFIRS4p38Sf1_k17fTqzoc9uMqyuGSYWYrDKYXRXO5qz58U2TBhAH227B39WMvZP2k6lmNrACS3YRvPJ1v_cIR5aueWAwul2IHriVweKCdtn8pvT1ZYZK37aH-I7fjbDUExbb6ORvqN-HJyw0vuyCV5zYGemezsRMtB4b5D6F6qmjrHpq6zyWFN3_pyn_VsZbhY9hWomEddFE2uiNbgbZ2Rzq7eFzWPBMG2c6ugCF2gg0noWryoiuzt44wj0Fc70-2ASqy9XQMXnv2sMDD029fwCkRuqPDaW5KC_84DEIXK0BPO-XQhUKgzNBsiPkRuoHx572xmG7Slrqx_6852F2aOhos1kFdS4ZQhRn1Wnbc9w0q_FSUG2f8vquBM8lbFUmvh7cKdvc6qqzDGySHjqUvj5ybcJX7SE0My_JWBFbixUAIwXGE9qTJKkN9h4f538uTto4eOGjMfGYLKuudeEImnWYhhZ3n5jIGMAXNWFr1tm-yjWm5_MFaYhc0YCIvwPLN27_9AR_j4fDjlvay3gSRqD_CsZMXHHup6zhdI0vg3k8Wi0eVVIlKWG0DsGs5VqJbCmkjk9StONwSW65fEibTCCo6gPX8CJ6UlooVouqZO0427Esom6AT7IMW_89DUJYb89GpGaw5rKqyao2APsedcGIa3dbEuBLEBobeXvvvDVrNe6iZWl0fJGaZwfuhDL1ikryJymiejZ1OAVq6Q-4LERnjEyuu6kP6fagGfb0GvTpB5Lp9xqX9MC7iAZn4Yzt4XsdvlpGDxIv0KHK9Kug-FWYHAQ_ZMkp7zQ.rPSzGlkgDvprP5cba6StFw

#merchant:
#  get:
#    get-by-id: http://localhost:8080/merchant/merchants/
#
#customer:
#  get:
#    get-by-id: http://localhost:8080/customer/customers/

merchant:
  get:
    get-by-id: http://msgateway:8080/merchant/merchants/

customer:
  get:
    get-by-id: http://msgateway:8080/customer/customers/

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: actuator,logfile,metrics,health,info
      base-path: /v1/actuator