---
apiVersion: v1
kind: Service
metadata:
  name: msorder
  labels:
    app: msorder
spec:
  type: NodePort
  selector:
    app: msorder
  ports:
  - protocol: TCP
    port: 8085
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: msorder
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: msorder
    spec:
      containers:
      - name: msorder
        image: localhost:32000/msorder:latest
        ports:
        - containerPort: 8085
        livenessProbe:
          httpGet:
            path: v1/actuator/health
            port: 8085
          initialDelaySeconds: 30
          timeoutSeconds: 1
        # imagePullPolicy: Never