spring:
  application:
    name: auth
  data:
    mongodb:
      uri: ${MONGOURI}

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
