spring:
  application:
    name: auth
  data:
    mongodb:
      uri: mongodb://root:mongolocalprotavao@localhost:27017/DeliveryApp?authSource=admin

server:
  port: 8083

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${random.int}
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true

jwt:
  config:
    type: signed