export const AUTH_EMAIL_START = 'AUTH_EMAIL_START';
export const AUTH_EMAIL_SUCCESS = 'AUTH_EMAIL_SUCCESS';
export const AUTH_EMAIL_FAIL = 'AUTH_EMAIL_FAIL';

export const AUTH_PASSWORD_START = 'AUTH_PASSWORD_START';
export const AUTH_PASSWORD_SUCCESS = 'AUTH_PASSWORD_SUCCESS';
export const AUTH_PASSWORD_FAIL = 'AUTH_PASSWORD_FAIL';

export const AUTH_RESET = 'AUTH_RESET';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SIGNUP_RESET = 'SIGNUP_RESET';
export const ERROR_RESET = 'ERROR_RESET';
