/*---------------------------------- AUTH ----------------------------------*/
export const AUTH_EMAIL_START = 'AUTH_EMAIL_START';
export const AUTH_EMAIL_SUCCESS = 'AUTH_EMAIL_SUCCESS';
export const AUTH_EMAIL_FAIL = 'AUTH_EMAIL_FAIL';

export const AUTH_PASSWORD_START = 'AUTH_PASSWORD_START';
export const AUTH_PASSWORD_SUCCESS = 'AUTH_PASSWORD_SUCCESS';
export const AUTH_PASSWORD_FAIL = 'AUTH_PASSWORD_FAIL';

/*--------------------------------- CUSTOMER ---------------------------------*/
export const CUSTOMER_SIGNUP_START = 'CUSTOMER_SIGNUP_START';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';

export const CUSTOMER_DATA_START = 'CUSTOMER_DATA_START';
export const CUSTOMER_DATA_SUCCESS = 'CUSTOMER_DATA_SUCCESS';
export const CUSTOMER_DATA_FAIL = 'CUSTOMER_DATA_FAIL';

export const CUSTOMER_EDIT_DATA_START = 'CUSTOMER_EDIT_DATA_START';
export const CUSTOMER_EDIT_DATA_SUCCESS = 'CUSTOMER_EDIT_DATA_SUCCESS';
export const CUSTOMER_EDIT_DATA_FAIL = 'CUSTOMER_EDIT_DATA_FAIL';

export const CUSTOMER_NEW_ADDRESS_START = 'CUSTOMER_NEW_ADDRESS_START';
export const CUSTOMER_NEW_ADDRESS_SUCCESS = 'CUSTOMER_NEW_ADDRESS_SUCCESS';
export const CUSTOMER_NEW_ADDRESS_FAIL = 'CUSTOMER_NEW_ADDRESS_FAIL';

export const CUSTOMER_EDIT_ADDRESS_START = 'CUSTOMER_EDIT_ADDRESS_START';
export const CUSTOMER_EDIT_ADDRESS_SUCCESS = 'CUSTOMER_EDIT_ADDRESS_SUCCESS';
export const CUSTOMER_EDIT_ADDRESS_FAIL = 'CUSTOMER_EDIT_ADDRESS_FAIL';

export const CUSTOMER_REMOVE_ADDRESS_START = 'CUSTOMER_REMOVE_ADDRESS_START';
export const CUSTOMER_REMOVE_ADDRESS_SUCCESS =
  'CUSTOMER_REMOVE_ADDRESS_SUCCESS';
export const CUSTOMER_REMOVE_ADDRESS_FAIL = 'CUSTOMER_REMOVE_ADDRESS_FAIL';

/*--------------------------------- LOCATES ---------------------------------*/
export const FETCH_STATES_START = 'FETCH_STATES_START';
export const FETCH_STATES_SUCCESS = 'FETCH_STATES_SUCCESS';
export const FETCH_STATES_FAIL = 'FETCH_STATES_FAIL';

export const FETCH_CITIES_START = 'FETCH_CITIES_START';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAIL = 'FETCH_CITIES_FAIL';

export const FETCH_ADDRESS_START = 'FETCH_ADDRESS_START';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAIL = 'FETCH_ADDRESS_FAIL';

/*--------------------------------- MERCHANT ---------------------------------*/
export const MERCHANT_SIGNUP_START = 'MERCHANT_SIGNUP_START';
export const MERCHANT_SIGNUP_SUCCESS = 'MERCHANT_SIGNUP_SUCCESS';
export const MERCHANT_SIGNUP_FAIL = 'MERCHANT_SIGNUP_FAIL';

export const MERCHANT_DATA_START = 'MERCHANT_DATA_START';
export const MERCHANT_DATA_SUCCESS = 'MERCHANT_DATA_SUCCESS';
export const MERCHANT_DATA_FAIL = 'MERCHANT_DATA_FAIL';

export const MERCHANT_EDIT_DATA_START = 'MERCHANT_EDIT_DATA_START';
export const MERCHANT_EDIT_DATA_SUCCESS = 'MERCHANT_EDIT_DATA_SUCCESS';
export const MERCHANT_EDIT_DATA_FAIL = 'MERCHANT_EDIT_DATA_FAIL';

export const MERCHANT_PUT_CATEGORIES_START = 'MERCHANT_PUT_CATEGORIES_START';
export const MERCHANT_PUT_CATEGORIES_SUCCESS =
  'MERCHANT_PUT_CATEGORIES_SUCCESS';
export const MERCHANT_PUT_CATEGORIES_FAIL = 'MERCHANT_PUT_CATEGORIES_FAIL';

/*--------------------------------- RESETS ---------------------------------*/
export const AUTH_RESET = 'AUTH_RESET';
export const SIGNUP_RESET = 'SIGNUP_RESET';
export const ERROR_RESET = 'ERROR_RESET';
export const LOCATE_RESET = 'LOCATE_RESET';
