export const AUTH_EMAIL_START = 'AUTH_EMAIL_START';
export const AUTH_EMAIL_SUCCESS = 'AUTH_EMAIL_SUCCESS';
export const AUTH_EMAIL_FAIL = 'AUTH_EMAIL_FAIL';

export const AUTH_PASSWORD_START = 'AUTH_PASSWORD_START';
export const AUTH_PASSWORD_SUCCESS = 'AUTH_PASSWORD_SUCCESS';
export const AUTH_PASSWORD_FAIL = 'AUTH_PASSWORD_FAIL';

export const AUTH_RESET = 'AUTH_RESET';
