export const categories = {
  AFRICANA: 'Africana',
  ALEMA: 'Alemã',
  ARABE: 'Árabe',
  ARGENTINA: 'Argentina',
  ASIATICA: 'Asiática',
  ACAI: 'Açai',
  BAIANA: 'Baiana',
  BEBIDAS: 'Bebidas',
  BRASILEIRA: 'Brasileira',
  CAFETERIA: 'Cafeteria',
  CARNES: 'Carnes',
  CASA_DE_SUCOS: 'Casa de Sucos',
  CHINESA: 'Chinesa',
  COLOMBIANA: 'Colombiana',
  CONGELADOS_FIT: 'Congelados Fit',
  CONGELADOS: 'Congelados',
  CONTEMPORANEA: 'Contemporânea',
  CONVENIENCIA: 'Conveniência',
  COREANA: 'Coreana',
  COZINHA_RAPIDA: 'Cozinha Rápida',
  CREPE: 'Crepe',
  DOCES_BOLOS: 'Doces e Bolos',
  ESPANHOLA: 'Espanhola',
  FRANCESA: 'Francesa',
  FRANGOS: 'Frangos',
  FRUTOS_DO_MAR: 'Frutos do Mar',
  GAUCHA: 'Gaúcha',
  GREGA: 'Grega',
  HAMBURGUER: 'Hambúrguer',
  INDIANA: 'Indiana',
  ITALIANA: 'Italiana',
  JAPONESA: 'Japonesa',
  LANCHES: 'Lanches',
  MARMITA: 'Marmita',
  MARROQUINA: 'Marroquina',
  MEDITERRANEA: 'Mediterrânea',
  MERCADO: 'Mercado',
  MEXICANA: 'Mexicana',
  MINEIRA: 'Mineira',
  NORDESTINA: 'Nordestina',
  PADARIA: 'Padaria',
  PANQUECA: 'Panqueca',
  PARANAENSE: 'Paranaense',
  PASTEL: 'Pastel',
  PEIXES: 'Peixes',
  PERUANA: 'Peruana',
  PIZZA: 'Pizza',
  PORTUGUESA: 'Portuguesa',
  PRESENTES: 'Presentes',
  SALGADOS: 'Salgados',
  SAUDAVEL: 'Saudável',
  SOPAS_CALDOS: 'Sopas e Caldos',
  SORVETES: 'Sorvetes',
  TAILANDESA: 'Tailandesa',
  TAPIOCA: 'Tapioca',
  TIPICA_NORTE: 'Típica do Norte',
  VARIADA: 'Variada',
  VEGANA: 'Vegana',
  VEGETARIANA: 'Vegatariana',
  XIS: 'Xis',
  YAKISOBA: 'Yakisoba',
};
