server:
  port: 8081

spring:
  application:
    name: customer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: X
    username: X
    password: X
  cloud:
    stream:
      bindings:
        #outputs
        output-save-customer:
          destination: customer-channel
          group: save-customer
        output-update-customer:
          destination: customer-channel
          group: update-customer
        output-delete-customer:
          destination: customer-channel
          group: delete-customer
        #inputs
        input-save-customer:
          destination: customer-channel
          group: save-customer-queue
        input-update-customer:
          destination: customer-channel
          group: update-customer-queue
        input-delete-customer:
          destination: customer-channel
          group: delete-customer-queue

      rabbit:
        bindings:
          #outputs
          output-save-customer:
            producer:
              bindingRoutingKey: saveCustomerBinding
              routingKeyExpression: '"saveCustomerBinding"'
          output-update-customer:
            producer:
              bindingRoutingKey: updateCustomerBinding
              routingKeyExpression: '"updateCustomerBinding"'
          output-delete-customer:
            producer:
              bindingRoutingKey: deleteCustomerBinding
              routingKeyExpression: '"deleteCustomerBinding"'
          #inputs
          input-save-customer:
            consumer:
              bindingRoutingKey: saveCustomerBinding
              routingKeyExpression: '"saveCustomerBinding"'
              acknowledgeMode: AUTO
              declareExchange: false
              bindQueue: false
              queueNameGroupOnly: true
          input-update-customer:
            consumer:
              bindingRoutingKey: updateCustomerBinding
              routingKeyExpression: '"updateCustomerBinding"'
              acknowledgeMode: AUTO
              declareExchange: false
              bindQueue: false
              queueNameGroupOnly: true
          input-delete-customer:
            consumer:
              bindingRoutingKey: deleteCustomerBinding
              routingKeyExpression: '"deleteCustomerBinding"'
              acknowledgeMode: AUTO
              declareExchange: false
              bindQueue: false
              queueNameGroupOnly: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
