server:
  port: 8081

spring:
  application:
    name: customer
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: X
    username: X
    password: X
  cloud:
    stream:
      bindings:
        product-channel:
          destination: product-process
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
