server:
  port: 8888
spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MarcosVMoreira/iFood-Clone
          searchPaths: configuration-files/*service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    fetch-registry: true
    register-with-eureka: true