apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - name: rabbitmq
      port: 5672
      nodePort: 30001
    - name: dashboard
      port: 15672
      nodePort: 30002
  selector:
    app: rabbitmq
